name: Build Backend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs:
      - eslint
      - prettier
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build Backend
        run: cd packages/backend && yarn build
